pophory-iOS.xcodeproj/project.pbxproj
pophory-iOS/Global/Extensions/UILabel+Extension.swift
pophory-iOS/Global/Resources/SceneDelegate.swift

SceneDelegate, UILabel+Extension 수정했습니다.

[Setting] #6 - SceneDelegate, UILabel+Extension 수정

---

pophory-iOS/Global/Consts/FontLiterals.swift
pophory-iOS/Global/Supporting Files/Info.plist

피그마에 업데이트된 가이드 따라서 FontLiterals 수정 했습니다!
- Resolved: #9

[Setting] #9 - FontLiterals 수정

---

pophory-iOS/Global/Components/Base/BaseView.swift

BaseViewController 수정했습니다.
- Resolved: #12

[Chore] #12 - BaseViewController 수정

---

pophory-iOS/Global/Components/Base/BaseViewController.swift

BaseViewController 수정했습니다
- Resolved: #14

[Chore] #14 - BaseViewController 수정

---

pophory-iOS.xcodeproj/project.pbxproj

[Chore] #18 - 빌드오류 수정

---

pophory-iOS.xcodeproj/project.pbxproj
pophory-iOS/Global/Protocols/Navigatable.swift

[ADD] protocol navigatable

---

pophory-iOS/Global/Consts/ColorLiterals.swift

[ADD] 디자인 패턴 색상 추가

---

pophory-iOS/Screen/AddPhoto/View/PhotoAlbumCollectionViewCell.swift
pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
pophory-iOS/Screen/AddPhoto/ViewController/StudioModalViewController.swift

사진 추가 뷰의 앨범, 사진관 API 연결 (GET)
|1|2|3|
|---|---|---|
|![Simulator Screenshot - iPhone 13 mini - 2023-07-07 at 02 55 13](https://github.com/TeamPophory/pophory-iOS/assets/75093565/3cff663d-bd30-4695-b453-9f20b40e7cc5)|![Simulator Screenshot - iPhone 13 mini - 2023-07-07 at 02 55 20](https://github.com/TeamPophory/pophory-iOS/assets/75093565/845b5864-3464-4410-8933-fac796ab5280)|![Simulator Screenshot - iPhone 13 mini - 2023-07-07 at 02 55 24](https://github.com/TeamPophory/pophory-iOS/assets/75093565/67724532-7f25-4e13-b196-ebf7fc6c02da)
- Resolved: #58

[Feat] #58 사진 추가 뷰 - 앨범, 사진관 API 연결

---

pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
pophory-iOS/Screen/PhotoDetail/View/PhotoDetailView.swift
pophory-iOS/Screen/PhotoDetail/ViewController/PhotoDetailViewController.swift

#59 브랜치 코드리뷰 반영
- Resolved: #79

[Fix] #79 #59 브랜치 코드리뷰 반영

---

pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift

- 일러스트 터치 방지 로직 구현
- Resolved: #85

[Add] 일러스트 터치 방지 로직 구현

---

pophory-iOS/Global/Extensions/UIViewController+Extension.swift
pophory-iOS/Global/Resources/SceneDelegate.swift
pophory-iOS/Network/Common/BaseTargetType.swift
pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
pophory-iOS/Screen/Auth/PickAlbumCoverViewController.swift
pophory-iOS/Screen/Auth/StartPophoryViewController.swift
pophory-iOS/Screen/HomeAlbum/HomeAlbumView.swift
pophory-iOS/Screen/HomeAlbum/HomeAlbumViewController.swift

[Add] 네비게이션 연결

---

pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift

- maxId 값 추출 방식 변경
- Resolved: #93

[Add] maxId 값 추출 방식 변경

---

pophory-iOS/Global/Consts/ImageLiterals.swift
pophory-iOS/Screen/Auth/PickAlbumButtonCollectionViewCell.swift
pophory-iOS/Screen/Auth/Views/PickAlbumCoverView.swift
pophory-iOS/Screen/Auth/Views/StartPophoryView.swift

[Add] #92 온보딩 일러스트 추가

---

pophory-iOS/Screen/AddPhoto/View/AddPhotoView.swift
pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift

#101 릴리즈를 위한 준비중 기능 삭제
- Resolved: #101

[Chore] #101 릴리즈를 위한 준비중 기능 삭제

---

pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift

사진 추가 뷰 albumID, studioID 기본 값 수정
사진 추가 시 홈 앨범의 사진 개수 반영되도록 수정
- Resolved: #104

[Chore] #104 사진 추가 뷰 네트워크 수정

---

pophory-iOS/Global/Consts/FontLiterals.swift
pophory-iOS/Global/Consts/ImageLiterals.swift
pophory-iOS/Global/Resources/Assets.xcassets/ckeckBigIconWhite.imageset/Contents.json
pophory-iOS/Global/Resources/Assets.xcassets/ckeckBigIconWhite.imageset/ckeckBigIconWhite.svg
pophory-iOS/Screen/AddPhoto/View/AddPhotoView.swift
pophory-iOS/Screen/AddPhoto/View/PhotoAlbumCollectionViewCell.swift
pophory-iOS/Screen/AddPhoto/View/PhotoInfoStackView.swift
pophory-iOS/Screen/AddPhoto/View/StudioCollectionViewCell.swift
pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift
pophory-iOS/Screen/AddPhoto/ViewController/StudioModalViewController.swift

사진 추가 뷰 UI 수정
1. 폰트 수정
2. 앨범 선택 시 체크표시 구현 (기본 선택되어이있음)
- Resolved: #96

[Chore] #96 사진 추가 뷰 UI 수정

---

pophory-iOS.xcodeproj/project.pbxproj
pophory-iOS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
pophory-iOS/Global/Components/Base/BaseViewController.swift
pophory-iOS/Global/Components/PophoryPopupView.swift
pophory-iOS/Global/Components/PophoryWebViewController.swift
pophory-iOS/Global/Extensions/UserDefault+Extension.swift
pophory-iOS/Network/Common/BaseURLConstant.swift
pophory-iOS/Screen/AlbumDetail/View/PhotoCollectionViewCell.swift
pophory-iOS/Screen/Auth/IDInputViewController.swift
pophory-iOS/Screen/Auth/PickAlbumCoverViewController.swift
pophory-iOS/Screen/Mypage/Network/MyPageNetworkManager.swift
pophory-iOS/Screen/Mypage/View/MyPageRootView.swift
pophory-iOS/Screen/Mypage/ViewController/MypageViewController.swift
pophory-iOS/Screen/Settings/View/SettingsRootView.swift
pophory-iOS/Screen/Settings/ViewController/SettingsViewController.swift

- 마이페이지, 설정뷰 API 연결
- Resolved: #111

[Feat] 마이페이지, 설정 API 연결

---

pophory-iOS/Network/Common/BaseURLConstant.swift
pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
pophory-iOS/Screen/HomeAlbum/HomeAlbumViewController.swift

Home에서 앨범이 빈 배열일 때 albums?[0]으로 인덱스 접근 시 앱이 터지는 문제 해결
앨범 ID 값이 Test Token인 부분 수정
- Resolved: #119

[Feat] #119 앨범 빈 배열 & 앨범 ID 값 수정

---

pophory-iOS/Global/Components/PophoryNavigationConfigurator.swift
pophory-iOS/Global/Components/PophoryWebViewController.swift
pophory-iOS/Global/Extensions/UIViewController+Extension.swift
pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
pophory-iOS/Screen/AlbumDetail/View/AlbumDetailView.swift
pophory-iOS/Screen/Auth/ViewControllers/IDInputViewController.swift
pophory-iOS/Screen/Auth/ViewControllers/NameInputViewController.swift
pophory-iOS/Screen/Auth/ViewControllers/PickAlbumCoverViewController.swift
pophory-iOS/Screen/Mypage/View/MyPageRootView.swift
pophory-iOS/Screen/Onboarding/ViewContoller/OnboardingViewController.swift
pophory-iOS/Screen/Settings/ViewController/SettingsViewController.swift

- 자잘한 버그들 수정했습니다. (넘 많아서 하나하나 적기 귀찮고.. 커밋 로그 봐주세요 ㅋㅋ)
- Resolved: #129

[Fix] 자잘한 버그들 수정

---

pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
pophory-iOS/Screen/HomeAlbum/HomeAlbumViewController.swift

앨범 ID 서버 데이터 적용
- Resolved: #137

[Fix] 앨범 ID 서버 데이터 적용

---

pophory-iOS/Network/API/PhotoAPI.swift
pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift

test token -> 실제 토큰 Photo API Header 수정
AddPhotoViewController에서 AlbumID 값 수정
- Resolved: #139

[Fix] #139 PhotoAPI 수정 및 AddPhoto AlbumID 수정

---

pophory-iOS/Global/Components/Base/BaseViewController.swift
pophory-iOS/Global/Components/PophoryNavigationConfigurator.swift
pophory-iOS/Network/API/PhotoAPI.swift
pophory-iOS/Screen/AlbumDetail/AlbumDetailViewController.swift
pophory-iOS/Screen/PhotoDetail/ViewController/PhotoDetailViewController.swift

사진 삭제 API를 연결했습니다
추가로 NavigationBar의 RightButton에 case setting을 사용하지 않는 것 같아 수정해줬습니다.
https://github.com/TeamPophory/pophory-iOS/assets/75093565/6eb3e623-094d-45f2-a091-5ac9f9f8b5ba
- Resolved: #115

[Feat] #115 사진 삭제 API 연결

---

pophory-iOS/Screen/AddPhoto/ViewController/AddPhotoViewController.swift

사진 다 찼을 시 팝업 구현
https://github.com/TeamPophory/pophory-iOS/assets/75093565/233de8f8-7206-486c-86d8-48fa1910b977
- Resolved: #144

[Add] #144 사진 다 찼을 시 팝업 구현

---

pophory-iOS.xcodeproj/project.pbxproj
pophory-iOS/Global/Components/Base/BaseInputView.swift
pophory-iOS/Global/Extensions/CGSize+Extension.swift
pophory-iOS/Global/Extensions/ConstraintMaker+Extension.swift
pophory-iOS/Global/Extensions/UIView+Extension.swift
pophory-iOS/Global/Resources/SceneDelegate.swift
pophory-iOS/Global/Utilities/KeyboardManager.swift
pophory-iOS/Network/Common/BaseURLConstant.swift
pophory-iOS/Screen/Auth/ViewControllers/IDInputViewController.swift
pophory-iOS/Screen/Auth/ViewControllers/NameInputViewController.swift
pophory-iOS/Screen/Auth/ViewControllers/PickAlbumCoverViewController.swift
pophory-iOS/Screen/Auth/Views/PickAlbumCoverView.swift
pophory-iOS/Screen/Auth/Views/StartPophoryView.swift
pophory-iOS/Screen/HomeAlbum/HomeAlbumView.swift
pophory-iOS/Screen/Onboarding/View/Cell/OnboardingContentCollectionViewCell.swift
pophory-iOS/Screen/Onboarding/View/OnboardingView.swift
pophory-iOS/Screen/Onboarding/ViewContoller/OnboardingViewController.swift

[Fix] - 기기대응

---

pophory-iOS/Global/Components/Base/BaseInputView.swift
pophory-iOS/Global/Resources/SceneDelegate.swift
pophory-iOS/Screen/Auth/Views/IDInputView.swift
pophory-iOS/Screen/Auth/Views/NameInputView.swift
pophory-iOS/Screen/Auth/Views/PickAlbumCoverView.swift
pophory-iOS/Screen/Onboarding/View/OnboardingView.swift

* 정규식 작성정책, UX 라이팅 변경했습니다.
- Resolved: #135

[Chore] #135 - 정규식 작성정책, UX라이팅 변경
